/**
 * Human-readable messages for FPX debitAuthCode values.
 * Extend or edit here only.
 */
export const FPX_CODE_MSG: Record<string, string> = {
  '00': 'Approved',
  '03': 'Invalid Merchant',
  '05': 'Invalid Seller / Acquiring Bank Code',
  '09': 'Transaction Pending',
  '12': 'Invalid Transaction',
  '13': 'Invalid Amount',
  '14': 'Invalid Buyer Account',
  '20': 'Invalid Response',
  '30': 'Format Error',
  '31': 'Invalid Bank',
  '39': 'No Credit Account',
  '45': 'Duplicate Seller Order Number',
  '46': 'Invalid Seller Exchange / Seller',
  '47': 'Invalid Currency',
  '48': 'Maximum Transaction Limit Exceeded',
  '49': 'Merchant-Specific Limit Exceeded',
  '50': 'Invalid Seller for Merchant-Specific Limit',
  '51': 'Insufficient Funds',
  '53': 'No Buyer Account Number',
  '57': 'Transaction Not Permitted',
  '58': 'Transaction To Merchant Not Permitted',
  '70': 'Invalid Serial Number',
  '76': 'Transaction Not Found',
  '77': 'Invalid Buyer Name / Buyer ID',
  '78': 'Decryption Failed',
  '79': 'Host Decline When Down',
  '80': 'Buyer Cancel Transaction',
  '83': 'Invalid Transaction Model',
  '84': 'Invalid Transaction Type',
  '85': 'Internal Error At Bank System',
  '87': 'Debit Failed – Exception Handling',
  '88': 'Credit Failed – Exception Handling',
  '89': 'Transaction Not Received – Exception Handling',
  '90': 'Bank Internet Banking Unavailable',
  '92': 'Invalid Buyer Bank',
  '96': 'System Malfunction',
  '98': 'MAC Error',
  '99': 'Pending Authorisation',
  'BB': 'Blocked Bank',
  'BC': 'Transaction Cancelled By Customer',
  'DA': 'Invalid Application Type',
  '2X': 'Transaction Cancelled By Merchant'
};
